
/* Auto generated by Glue Client Compiler tool (gluec) 
on 25.11.2015 22:09:21 at PC by 1
Do not modify this file by hand if you plan to regenerate this file again by the tool as manual changes will be lost
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

using NFX.Glue;
using NFX.Glue.Protocol;


namespace Glue.Contracts.Services.GluedClients
{
  ///<summary>
  /// Client for glued contract Glue.Contracts.Services.IHighLoadService server.
  /// Each contract method has synchronous and asynchronous versions, the later denoted by 'Async_' prefix.
  /// May inject client-level inspectors here like so:
  ///   client.MsgInspectors.Register( new YOUR_CLIENT_INSPECTOR_TYPE());
  ///</summary>
  public class HighLoadServiceClient : ClientEndPoint, @Glue.@Contracts.@Services.@IHighLoadService
  {

  #region Static Members

     private static TypeSpec s_ts_CONTRACT;
     private static MethodSpec @s_ms_Ping1_0;
     private static MethodSpec @s_ms_Ping2_1;

     //static .ctor
     static HighLoadServiceClient()
     {
         var t = typeof(@Glue.@Contracts.@Services.@IHighLoadService);
         s_ts_CONTRACT = new TypeSpec(t);
         @s_ms_Ping1_0 = new MethodSpec(t.GetMethod("Ping1", new Type[]{  }));
         @s_ms_Ping2_1 = new MethodSpec(t.GetMethod("Ping2", new Type[]{  }));
     }
  #endregion

  #region .ctor
     public HighLoadServiceClient(string node, Binding binding = null) : base(node, binding) { ctor(); }
     public HighLoadServiceClient(Node node, Binding binding = null) : base(node, binding) { ctor(); }
     public HighLoadServiceClient(IGlue glue, string node, Binding binding = null) : base(glue, node, binding) { ctor(); }
     public HighLoadServiceClient(IGlue glue, Node node, Binding binding = null) : base(glue, node, binding) { ctor(); }

     //common instance .ctor body
     private void ctor()
     {

     }

  #endregion

     public override Type Contract
     {
       get { return typeof(@Glue.@Contracts.@Services.@IHighLoadService); }
     }



  #region Contract Methods

         ///<summary>
         /// Synchronous invoker for  'Glue.Contracts.Services.IHighLoadService.Ping1'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         ///</summary>
         public void @Ping1()
         {
            var call = Async_Ping1();
            if (call.CallStatus != CallStatus.Dispatched)
                throw new ClientCallException(call.CallStatus, "Call failed: 'HighLoadServiceClient.Ping1'");
         }

         ///<summary>
         /// Asynchronous invoker for  'Glue.Contracts.Services.IHighLoadService.Ping1'.
         /// This is a one-way call per contract specification, meaning - the server sends no acknowledgement of this call receipt and
         /// there is no result that server could return back to the caller.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg.
         ///</summary>
         public CallSlot Async_Ping1()
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Ping1_0, true, RemoteInstance, new object[]{});
            return DispatchCall(request);
         }



         ///<summary>
         /// Synchronous invoker for  'Glue.Contracts.Services.IHighLoadService.Ping2'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or RemoteExceptionData instance.
         /// ClientCallException is thrown if the call could not be placed in the outgoing queue.
         /// RemoteException is thrown if the server generated exception during method execution.
         ///</summary>
         public void @Ping2()
         {
            var call = Async_Ping2();
            call.CheckVoidValue();
         }

         ///<summary>
         /// Asynchronous invoker for  'Glue.Contracts.Services.IHighLoadService.Ping2'.
         /// This is a two-way call per contract specification, meaning - the server sends the result back either
         ///  returning no exception or RemoteExceptionData instance.
         /// CallSlot is returned that can be queried for CallStatus, ResponseMsg and result.
         ///</summary>
         public CallSlot Async_Ping2()
         {
            var request = new RequestAnyMsg(s_ts_CONTRACT, @s_ms_Ping2_1, false, RemoteInstance, new object[]{});
            return DispatchCall(request);
         }


  #endregion

  }//class
}//namespace
