$(document).ready(function () {
  var divTitle = $('#title');
  divTitle.text('This text was generated by a script');
  divTitle.css({ 'color': '#37699a', 'font-size': '20px', 'font-weight': 'bold' });
});